# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6408f3e34f35e48cab255527a8545f2fd900dcbe32a3bf1501fb12a44504e7b86863772d62eac5f22bc7fef0b1222183c584412189ba4c361146c23728d697a

test:
  secret_key_base: 390f32b6aeba985a4a0fb59612b49fa8d9076c5b554315fa701eb91e4c4ef814449617962e2650fd79e4531df47b6b5256fdc9d359af34feba6cfde5550e3eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
